name: deploy-payments

on:
  push:
    branches:
      - master
    paths:
      - 'payments/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && docker build -t humam/payments .
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB.USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB.PASSWORD }}
      - run: docker push humam/payments
      - uses: digitalocean/action-doctl@v2
        with: 
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketit
      - run: kubectl rollout restart deployment payments-depl