name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - run: cd auth && docker build -t humam/auth .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p {{ secrets.DOCKER_PASSWORD }}
        env:
          $DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          $DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push humam/auth
      - uses: digitalocean/action-doctl@v2
        with: 
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketit
      - run: kubectl rollout restart deployment auth-depl
