name: deploy-expiration

on:
  push:
    branches:
      - master
    paths:
      - 'expiration/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t humam/expiration .
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB.USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB.PASSWORD }}
      - run: docker push humam/expiration
      - uses: digitalocean/action-doctl@v2
        with: 
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketit
      - run: kubectl rollout restart deployment expiration-depl