name: tests-payments

on:
  pull_request:
    paths:
      - 'payments/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: cd payments && npm install && npm run test:ci
