name: tests-orders

on:
  pull_request:
    paths:
      - 'orders/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: cd orders && npm install && npm run test:ci
